### ISSUE TITLE
Item Requirements

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#101]
A couple of more item requirement issues I've noticed after syncing with the latest data.

The new Ancient Platebody, Bandos Platebody ETC all have an attack requirement of level 40 instead of defence.

This applies to the platelegs, plateskirts and helmets too.

Dragon Boots have an attack requirement of 40 instead of defence. 

Void equipment is missing the 42 defence requirement.

Will update if I find more.

Jamie

**Comment by osrsbox** [comment]
Thanks @jburleigh1 for identifying these issues. I have just fixed them, so the new database update this week will have these fixed. The `item-skill-requirements.json` file was fixed in 52f696ad9355c65d2ea93230a179c92bae125c96, and the next commit will add this into the actual item JSON files.
