### ISSUE TITLE
Item Requirements

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#103]
A few more item requirement issues reported by my users:

Samurai Kasa has requirements of null, should have 35 defence.
Gilded Boots have requirements of 60 attack, should be 60 defence.
The duplicate Dragon Platelegs within the data is showing as  60 attack instead of 60 defence.
Gold Helmet has showing as null, should have 30 defence requirement.

That is all for now :)

**Comment by osrsbox** [comment]
Many thanks @jburleigh1 - these issues really help clean up the data. Have been trying to fix ASAP so that you can update on your site.

**Comment by jburleigh1** [comment]
Thank you!

three more for you! (should have realised this when I noticed the Samurai Kasa lol)

Samurai Shirt, Greaves and Boots should all have 35 def requirement!

**Comment by osrsbox** [comment]
Reopening issue to remind me to fix these.

**Comment by osrsbox** [comment]
@jburleigh1 - About to push the update which will fix these:

```
    "20038": {
        "defence": 35
    },
    "20041": {
        "defence": 35
    },
    "20044": {
        "defence": 35
    },
    "20047": {
        "defence": 35
    },
```

**Comment by osrsbox** [comment]
Closed in 29af212154a3d9b798201f188d7b6955131aae5f.

**Comment by jburleigh1** [comment]
Thank you Thomas!

**Comment by jburleigh1** [comment]
Some more issues reported last week:

The Robes of Darkness set is listed as null requirements, each item should have 20 defense and 40 magic requirements. IDs as follows:

Hood of darkness | 20128
-- | --

Robe top of darkness | 20131
-- | --

Gloves of darkness | 20134
-- | --

Robe bottom of darkness | 20137
-- | --

Boots of darkness | 20140
-- | --

There are also some passive requirements I'd like to request we add on all RFD gloves. These are requirements for the quests to unlock the item, rather than to actually equip the item.

Barrows Gloves | 7432 | Defence 41
-- | -- | --

Dragon Gloves | 7461 | Defence 41
-- | -- | --

Rune Gloves | 7460 | Defence 35
-- | -- | --

Adamant Gloves | 7459 | Defence 13
-- | -- | --

That is all for the moment :) I'll have another list of passive requirements for the Achievement Diary gear coming.

Jamie

**Comment by jburleigh1** [comment]
One more!

Dragon Platelegs are still showing as 60 attack, they should be:

Dragon Platelegs | 4180 | Defence 60
-- | -- | --

**Comment by osrsbox** [comment]
Reopening to remind me to fix. Many thanks @jburleigh1 for helping with these erroneous item requirements.

**Comment by jburleigh1** [comment]
Hey Thomas,

I have another couple of issues reported by users. Would it be useful to you if instead of reporting the faults, I simply made the edits in the requirements file and put in a merge request?

**Comment by osrsbox** [comment]
I have fixed the issues listed above, just not yet closed this issue. However, I did not yet add the RFD gloves yet - will open a new issue about them. Just worried about including _soft requirements_ for items, as there are so many different requirements that we don't have. And unsure where to store them and how to handle them. But like you, I want that sort of data included!

And, always happy for a PR. It does make life easier for me. But I don't mind doing the updates myself either. I try to add them with the weekly update.

**Comment by jburleigh1** [comment]
Hey Thomas,

That's fine, I see where you're coming from with soft requirements. There's also the issue of Achievement Diary gear having loads of soft requirements, maybe that could all live in a separate file like the ammo requirements?

I have another item requirement fix for you :) Only one today.

Kitchen Knife | 7447 | Atack 40
-- | -- | --

**Comment by osrsbox** [comment]
@jburleigh1 - I will add the `Kitchen knife` in tomorrows database update. Thanks again for submitting these. I will open a new issue with the, so-called, _soft requirements_ for any future discussion and development. Sorry about the late reply. Work and RL has been crushing me at the moment!

**Comment by osrsbox** [comment]
We seem to have fixed any current issues with the item level/skill requirements. So will close this issue to keep the issues board clean and relevant.
