### ISSUE TITLE
Additional feature for item definitions Hair/Beard removal and Platebody/Chainbody

### ISSUE THREAD

**Issue by knd6065** [osrsbox/osrsbox-db#106]
Could we have added field for if head items have the beard removed and also if the hair is removed. Also for body items if they have sleeves or not (platebody vs chainbody sort of).

**Comment by osrsbox** [comment]
Hey @knd6065, do you know of any data source (e.g., OSRS cache, OSRS Wiki, or somewhere else) that this data can be pulled from? There are 488 unique head slot items and 299 unique body slot items in the current version of the game - so these will be pretty hard to manually determine and populate.

On another note, is there any reason for the data? It seems like a unique and odd request :)

**Comment by osrsbox** [comment]
This issue is considered stale. If you are still interested in this additional feature request (and have some idea on how to get the data) please feel free to re-open the issue.
