### ISSUE TITLE
split items_complete.json into items_SLOT.json

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#11]
Me again :)

Would you consider creating a seperate .json file for every item slot? 

So we'd end up with something like this:
```
/items_complete.json
/items_head.json
/items_cape.json
/...
```

This would allow developers to work with a much smaller set of data if only a single slot is needed, and also give us a dataset that only includes equippables and not 1000s of items that cannot be equipped.

**Comment by osrsbox** [comment]
Hey! This is an easy addition, as the Python API available has the functionality to easily handle processing the database contents (either the `items_complete.json` file or `items-json` directory). I wrote a Python script to process the database and create a JSON file for each slot. The script is available in the `item_api_tools` folder and is called `c_GenerateItemSlotFiles.py`. Each time I update the database contents I will also generate these files again.

The actual JSON files are in `docs/items-json-slot` folder and have the same naming convention you posted in your issue, e.g., `items_head.json`. They should be the same structure as all the other JSON files, where the item ID is the key and the item metadata is nested under each item ID key.

Hope that helps! Even looking quickly at the files, they are much smaller and easier to process.

The update will be in the next commit - which will close the issue.

**Comment by jburleigh1** [comment]
awesome, thanks so much for actioning this so quickly. This will make it much easier for me trying to make the switch between my own data and yours.
