### ISSUE TITLE
Author JSON schema for monster data

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#116]
As outlined in #16, we have been looking at adding monster data to the  `orsrbsox-db` project for a long time. I will have a lot more time in the next couple months to start development on this issue again.

To start it is essential to specify a schema for the data to be collected and stored. Similar to the [`item_schema.json`](https://github.com/osrsbox/osrsbox-db/blob/master/test/item_schema.json), a new JSON schema for monster data should be added to help the building process and testing of the OSRS monsters data.

**Comment by osrsbox** [comment]
Just added a new branch with the JSON schema and `pytest` module for the monster data. See 066be544d5ba38a0c2a495b5c67eaad276608a84 for the changes. If anyone has feedback please post, but there seems less interest in this data, so will continue with my overall plan.

**Comment by emerald000** [comment]
FYI: I am quite interested in the monster data. I have plans for a combat helper that would really appreciate a good source of monster info.

**Comment by osrsbox** [comment]
@emerald000 Oh! That's excellent... glad that you are interested. Feel free to provide any feedback on the general plans - the schema should outline the different monster properties that will be collected. So if you have any other requirements, or see something useful I have missed, please let me know :)

**Comment by emerald000** [comment]
I think an image (or link to one) of the monster would be nice. More info is probably needed too for some drops. Like F2P/P2P-only drops. Wilderness-only drops. On Task-only drops. Catacombs-only drops. Drops only during a quest. Probably more I forget.

**Comment by osrsbox** [comment]
Awesome! Thanks @emerald000 for the feedback. Those additions to the `drops` object is very useful. I will think about how to add them to make it logical and not add too many additional fields to the existing JSON structure.

**Comment by osrsbox** [comment]
Closed in commit 7aabb3f9006ab8e066943156b1b8286b9956aac6.
