### ISSUE TITLE
ISO8601 for dates?

### ISSUE THREAD

**Issue by gc** [osrsbox/osrsbox-db#118]
Rather than a string like `"27 May 2003"`, I think it'd be more useful to pre-parse this into a IS8601 date. This way we can easily format it in any way we like. There's also the obvious benefit that its in a standardized format, and we can more safely depend on the date being in a consistent format.

Only downside I can think of: If this data is coming from runewiki, its possible that it wont be fully consistent, e.g. `27th May 2003` vs `27 May 2003` vs `27th of May 2003` etc, and depending on how you're parsing it this might present an issue. The obvious solutions are a library which intelligently handles these formats, or just editing the outlying wiki pages to have the more consistent format.

For reference, I'm seeing this date format used on the items API, it may appear on other things I'm not aware of (and upcoming things like quests).

**Comment by osrsbox** [comment]
Hey @gc - I think this is a really good idea. But I am sitting here wondering why I did not use ISO8601 to begin with! I have used it in a couple of projects before, and agree that it is a great way to handle timestamps.

I am currently using the [`dateparser` package](https://pypi.org/project/dateparser/) to automatically parse the release date from the OSRS Wiki (after cleaning the entry), and it seems to work well. So the only thing that needs to be changed is converting the date into ISO8601 format and saving it in the JSON output. I do not think the JSON schema support date format, so it will still be a string check.

Unless you (or anyone else) has any feedback, I think the following format is the most suitable:

```
YYYY-MM-DD
2003-05-27
```

**Comment by gc** [comment]
Awesome! Sounds good, only thing that comes to mind is, as mentioned if a slightly different date is on the wiki.

**Comment by osrsbox** [comment]
The [`dateparser` package](https://pypi.org/project/dateparser/) library can handle the slightly different date format from the wiki. It automatically extracts the correct date, even when slightly different formats are used. I will go ahead and change the following to add support for ISO8601 format:

1. Change the `item-schema.json` file to use ISO8601 string dates for validation
1. Change the `items_builder` code to output ISO8601 date format
1. Regenerate the item database with the new date format
