### ISSUE TITLE
Include anchor in OSRSWiki URL

### ISSUE THREAD

**Issue by jakebellotti** [osrsbox/osrsbox-db#122]
Currently, all items include only the canonical URL of the OSRSWiki.
For example, consider items with variations such as untrimmed and trimmed skill capes, or potions with multiple doses. They will have multiple sets of data on the page, and you can like to a specific one by the anchor at the end of the URL.

An Attack Potion(2) currently has the URL of:
https://oldschool.runescape.wiki/w/Attack_potion
When it should be:
https://oldschool.runescape.wiki/w/Attack_potion#2_dose

**Comment by osrsbox** [comment]
Hey, thanks for pointing this out. This is quite an easy fix, and definitely worthwhile to add. I can take the `version#` property from the wikitext infobox and append it to the URL - this is not too much hassle as this property is readily available.

**Comment by osrsbox** [comment]
Just about to close this issue. The next commit will have the `wiki_url` populated with the correct anchor. Will also push the new PyPi version `1.1.20` will have this change implemented.
