### ISSUE TITLE
Items with colour variants parses incorrect data

### ISSUE THREAD

**Issue by jakebellotti** [osrsbox/osrsbox-db#124]
When an item has colour variants, the data isn't scraped correctly.
For example, the Graceful Hood:
https://oldschool.runescape.wiki/w/Graceful_hood

Has multiple different coloured variants. They have different examine descriptions, and release dates.

Normal variant: https://www.osrsbox.com/osrsbox-db/items-json/11850.json
Agility arena variant: https://www.osrsbox.com/osrsbox-db/items-json/21061.json

However, as seen in the above files, it only scrapes data for the regular version. This means release date and examine are incorrect. In other items, potentially other values could be incorrect.

**Comment by osrsbox** [comment]
I think this will be possible by comparing item inventory icons from the cache and determining what version (colorway) the item actually is... I have done this for other items such as brodo shields and castlewars armour. Doesn't seem like too much effort to add/fix.

**Comment by jakebellotti** [comment]
The wiki should have the item IDs on the info box, just make sure to check the data you scrape corresponds with the current item ID on the scraper end.

**Comment by osrsbox** [comment]
Just about to close this issue. The next commit will have this issue fixed - and have manually checked the graceful variants which all seem correct. Will also push the new PyPi version `1.1.20` will have this change implemented.
