### ISSUE TITLE
Items with the same name but different use scrape incorrect data

### ISSUE THREAD

**Issue by jakebellotti** [osrsbox/osrsbox-db#125]
For example, the Holy Symbol has a wearable version and a quest version that is not wearable. However, for both it shows the stats for the wearable version, and does not detect that it is a quest item, as well as a few other discrepancies. 

Holy symbol
https://www.osrsbox.com/osrsbox-db/items-json/1718.json

Holy symbol (Icthlarin's Little Helper)
https://www.osrsbox.com/osrsbox-db/items-json/4682.json

**Comment by osrsbox** [comment]
Crap! I thought that I got most of these items. Do you have a list of other similar items that are incorrect? When first going through the item list and normalising the names I thought I got most, but the are 20K+ items and knew I must had missed some (human error). I have been thinking of automated methods to find such items. Any ideas?

**Comment by jakebellotti** [comment]
https://oldschool.runescape.wiki/w/Special:Search?search=item+4682&profile=default&fulltext=1

Do a search with "item <item-id>" on the wiki and the first result is normally the correct item.
Then you can scrape the item ID on the page from this part:

`<span data-attr-param="id"><span data-attr-index="0">4682</span></span>`

To verify that.
