### ISSUE TITLE
Setup discord server to aid collaborative development

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#129]
It has been getting progressively more difficult to perform collaborative development using GitHub issues. After numerous requests, a discord server will be created to help solve this problem.

**Comment by gc** [comment]
This would be great! Happy to help if needed.

**Comment by osrsbox** [comment]
As promised, I have set up a dedicated discord server to help us collaborate more effectively. Happy to have help and input on the setup - as I have not used discord much. I have included the server invite link below, and will leave this issue open for a while so that people can see it:

[https://discord.gg/HFynKyr](https://discord.gg/HFynKyr)
