### ISSUE TITLE
Add API functionality to retrieve item information by item name

### ISSUE THREAD

**Issue by Austin-Schmidli** [osrsbox/osrsbox-db#137]
The existing API works very well for retrieving item information if users already know the item ID for the item they are looking-up. However, I can see many use cases that involve retrieving item information when you don't yet know the item ID. Currently, to get this behavior users must maintain some local mapping of item names to item IDs in order to be able to query the API for the appropriate item. 

I suggest adding the functionality to retrieve item information by item name. If the API supported querying by item name:
- It would simplify user workflow for querying items in many cases.
- Users would not need to maintain a local mapping of item IDs to item names.

Of course the obvious issue with querying by item name is that many items share names, so unlike with item IDs there is not a 1 to 1 mapping of item name to item stats. 

I see two options for resolving this issue:

1. For each item name, simply serve 1 item.json that we determine to be most useful (Methods for this described below). 

2. For each item name, serve an item.json that contains an array of all items that share that name. This gives more power to the user but requires them to do some additional work to identify which specific item they are actually looking for. They also have to parse the retrieved json differently since the item information will be wrapped in an array, unlike with queries by item ID. 

Option 1 is easier to use, but Option 2 is more powerful. Personally, I feel that Option 1 would satisfy the most user use-cases. Of course, providing both options is also possible (Presumably differentiated by just placing them at different endpoints). 

**Some Considerations:**

**Practicality**
I don't know if any practical limitations exist on the maximum total size of the data set. (How much hosting space is available?) There are currently just under 11,000 unique item names, so assuming no fundamental changes are made to how the API serves data, this feature would involve creating that many new .json files. (Or double if both Options are to be supported)

**name vs. wiki_name**
In the comments of issue #136 @osrsbox mentions that a wiki_name property is being created which will help differentiate between items that share a common name. When that property is added, should this feature support queries by actual item name or by wiki_name? I'm not sure which would be the best route to take. 

**Option 1 'Algorithms'**
For items with the same name, should the lowest item ID simply be assumed to be the 'real' and most-commonly used version of the item? Or should an algorithm be developed that compares the item properties to determine this? (Actively filter noted, placeholder items, favor items with higher value/alch cost, etc)

@osrsbox If you believe this feature is a viable contribution, I would be happy to try my hand at working it and creating a pull request.

**Comment by osrsbox** [comment]
Hey @Austin-Schmidli - sorry about the delay in replying. I really like this idea, it makes logical sense to have items represented by names to make it easier to fetch _useful_ data. To answer a couple of questions/ideas you presented:

1. **Practicality**: The JSON API is hosted here on GitHub under the `docs` folder. Everything under that folder is accessible using the prefix: `https://osrsbox.com/osrsbox-db/`. According to [GitHub](https://help.github.com/en/articles/what-is-my-disk-quota) there is a 1GB _soft limit_, and a 100GB _hard limit_. Currently the repo is about 300MB without any local branches, and 125MB without the git deltas and other git metadata. So there is more than enough space.

2. `name` vs. `wiki_name`: The project was just updated (in commit cc040ac87b5883813db9b5e5f39f08d6c110055e) with the `wiki_name` property. When implementing it, the `wiki_name` seems much more suitable. It is more descriptive, and works towards better identifying duplicate items. I think this property would be better to use to identify by name.

3. **Algorithms**. This is still a major problem in the item database. As discussed very briefly in #94, I think there needs to be another property added to the schema... something like `primary_item` or `item_status` that has a boolean (or similar) to identify the _"real"_ item, or _"most commonly used"_ item. Then this property could be used to filter the items with duplicate names.

4. Out of "Option 1" and "Option 2" - I like the first option, with just one item per name. Like you said, I think this covers most scenarios, and if not the user/dev can revert back to the current data set.

One major factor in this discussion - I don't really like the static JSON API that is currently available. I do like the PyPi package - it is really easy to filter/process items. It would be great to have an API that had the same functionality. I discussed with @gc about implementing a RESTful API which would provided much more flexibility. He gave the example: `api.com/items?tradeable=1` which would return JSON for all the `tradeable` items... but the same thing could be done for searching item names: `api.com/items?name=abyssal whip`, or any other property that was implemented in the API. But I am pushing for time developing this - maybe in the future.

Back on topic - I think adding new JSON files, organized by name would be a nice addition to the project. I would greatly appreciate the PR and more than happy to discuss/review the PR/help in any other way. TL;DR; of my thoughts:

1. Store new files under: `docs/items-json-names` to align with the current project structure. 
1. Use `wiki_name` property as it is more descriptive
1. Have only one entry/file per unique name
1. Have a module/script to auto generate the JSON files, as in-game updates will change the contents (a good place for the script would be `scripts/update_items/generate_item_name_files.py`)

**Comment by gc** [comment]
Downloading every item once, and then querying the data yourself (locally) is probably the better thing to do here, unless you're in a browser environment and its a browser client fetching the data, in which case, a real REST api is needed to have the query strings like: getting the 10 most valuable bow items `api.com/items?search=bow&tradeable=1&limit=10&sort=gp_value&order=descending`.

If I have some time I might look into working more on a REST api, I have a need for one too, I started work on one a while ago. My idea was basically to just scrape this repo once every 24hrs (and my own other data sources for things not in this repo).

**Comment by osrsbox** [comment]
Just to comment on the discussion... after reading the reply from @gc. Another way to more easily/efficiently get the item ID to item name mappings is to use the `items-summary.json` file. This is publicly available form: [`https://www.osrsbox.com/osrsbox-db/items-summary.json`](https://www.osrsbox.com/osrsbox-db/items-summary.json). The file is quite small (1.1MB) compared to downloading every JSON file, and contains a JSON object of JSON objects. Example content is provided below:

```
{
  "0": {
    "id": 0,
    "name": "Dwarf remains"
  },
  "1": {
    "id": 1,
    "name": "Toolkit"
  }
```

It doesn't have the `wiki_name` property, and is not filtered for duplicates, but could be useful for _scanning_ the item names, and finding the correct item ID. Maybe another file could be added which is another summary file that contains an object mapping `wiki_name` to item data. For example:

```
{
  "Dragon pickaxe": {                      # The wiki_name
    "id": 11920,                           # The item ID
    "name": "Dragon pickaxe"               # The name directly from the cache
  },
  "Dragon pickaxe (upgraded)": {
    "id": 12797,
    "name": "Dragon pickaxe"
  },
  "Dragon pickaxe(or)": {
    "id": 23677,
    "name": "Dragon pickaxe(or)"
  }
```

After thinking about it, this might be a better method to get the item name to item ID mapping. It would save space, and save repetition of the same data.

But yes! A real REST API that can be queried on multiple properties would be heavenly! Once the monsters and quest data is done, that is the next major project milestone. But feel free to write one @gc, happy to try help development where I can, and always happy to test etc. But for now, @Austin-Schmidli - I think a single summary file of wiki names might be a better option. What do you think?
