### ISSUE TITLE
api name search

### ISSUE THREAD

**Issue by luddeb123** [osrsbox/osrsbox-db#139]
I have not been able to find if you can search a name and get the item id out of it using the api.
If i have a list of items and i want to query it using python to get the id's and make a local list of just specific items. 

I have not found any way to search using the API for example "Seers Ring" and get the items matching that filter. Is this something that is already implemented or not going to be implemented. I know that the problem is multiple items with same name but maybe it returns all of the items matching the filter.

**Comment by osrsbox** [comment]
Hey @luddeb123 - I am assuming you are talking about the Python PyPi package API - if not please let me know and I can give an answer for the JSON API. 

Yes, you are correct, there is no built-in support to search the Python items API using item names. But this makes me think that adding the support would be a useful built-in feature. However, you can achieve this in your own Python code. For example:

```
from osrsbox import items_api

# Load the item database
all_db_items = items_api.load()

# Initialize an empty dictionary for storing item names -> item
all_db_items_names = dict()

# Loop the loaded item database contents
for item in all_db_items:
    if item.wiki_name:
        # If the item has a wiki_name property, add it to the dictionary
        all_db_items_names[item.wiki_name] = item

# Loop the dictionary that maps wiki_name -> item
for wiki_name, item in all_db_items_names.items():
    print(wiki_name)  # Just print the name
    print(item["cost"])  # As another example
```

You are also correct, that there may be duplicate names. In the above example, the code will populate the dictionary with the **last occurrence**, which could be changed by checking if the `key` in the dictionary already exists, then not adding it another occurrence. It also uses the `wiki_name` which is usually more descriptive than the `name` property which is taken directly from the cache. Below is another example, which works with your specific example of the `Seers ring`:

```
from osrsbox import items_api

all_db_items = items_api.load()

for item in all_db_items:
    if item.name == "Seers ring":
        print(item.wiki_name)
        print(vars(item))
```

You could be more flexible with the search and use something like: `if "seers ring" in item.name.lower()`. This should yield more results, items like `Seers ring (i)`.

All that being said... I could easily write a function and add it to search the Python item API for a specific name. This could ease processing required by the developer using the API. Please let me know what you think. And please let me know if you were talking about the JSON API, not the Python API. Hope this helps!

**Comment by osrsbox** [comment]
Considering this issue closed. Feel free to comment/reopen if it has not been answered or additional information is required. Thanks!
