### ISSUE TITLE
Monster database enhancements

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#143]
After working on issue #142 and fixing lots of small bugs in the monster database data, a selection of new issues have been found. These new issues are listed below:

- Add a boolean property to indicate if a drop is members only
- Fix issues when the item drop ID is not found (improved `items_api` lookup accuracy)
- Improve database generation performance (especially item name lookup for item drops)
- Improved `weaknesses` and `attack_type` property values, and updating in `monster_schema.json`

**Comment by MauriceBenink** [comment]
Small suggestion that would be awesome to add to the monster-data.
The type of monster (undead, dragon, fire, etc)
and all location where these monsters are

**Comment by osrsbox** [comment]
@MauriceBenink - thanks for the comment and ideas.

1. The type of monster might be difficult. The wiki has a category section for monsters... but this is only for slayer monsters. This property has a summary of the _type of slayer monster_, rather than the generic type of monster.  For example, a blue dragon and Vorkath both have the category `Blue dragon` - so it is more for slayer tasks than for the type of monster. Note to self: the wikitext property name is `cat`. To add, the `attack_type` might help classify the type of monster, especially things like dragon fire.

2. The location seems easier! I thought this would be really difficult, but the wiki has a section called `Locations` that looks like it can be easily parsed... but cleaning the data might be a challenge. What I really want... an in-game co-ordinate of the monster! I have written a RuneLite plugin which dumps NPC (and ground item) location data, but have yet to try collect data. Anyway, I think the OSRS world is much too large for me to map myself. Anyway, I will have a look into parsing the location data from wiki pages, and extracting:
    - The location name
    - The number of monsters per location
    - Any requirements for using the location

**Comment by osrsbox** [comment]
This issue (apart from the comment about location) has been slowly added to the monsters database - as I have been fixing issues in the last few weekly database updates.
