### ISSUE TITLE
Author and release public RESTful API for item and monster database

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#145]
This repository has been somewhat stable as of late. Weekly updates are running smoothly and the item/monster databases are getting much easier to regularly re-generate and manage. So it seems like a good time to implement some new functionality.

It has been mentioned by multiple users/devs that a proper RESTful API would be beneficial. So this seems like the next logical step in development. If anyone wants to request something specific, or wants me to take something into consideration when making the API - please leave a comment. I am unsure yet if the API code will be public, where it will be hosted etc. But API access will be open and free. Hopefully I can keep up with server costs etc.

This issue is more of a heads up that it is in the works, and has been for a couple weeks already. Always open to feedback, ideas, proposals etc. So feel free to comment.

**Comment by Yonkai** [comment]
Have you made any progress on this? How have you been tackling it?

I was considering writing a GraphQL implementation for the dataset myself for a project I'm working on, figure it would be similar to your python queries.

**Comment by osrsbox** [comment]
Hey @Yonkai - I started the initial development, then got sidetracked on other projects. The current plan was to implement a MongoDB with the [Eve Framework](http://docs.python-eve.org/en/stable/) and Swagger API documentation. Other solutions I looked at were using Flask, and Django - mainly for ease of implementation to use the existing Python API. After looking at numerous solutions, Eve seemed the easiest and most flexible. The main goal was to have rich queries. With Eve I can write minimal backend code and end up with queries such as:

```
http://example.com/api/items?where={"name":"Abyssal whip","duplicate":false,"equipable":true}
```

Just had a quick read of GraphQL - which looks interesting. I mainly haven't taken the next step as I was unsure of how I wanted to implement it. The Eve query syntax is strange to me, and I am used to using "traditional" API query syntax, such as:

```
http://example.com/api/items?name=Abyssal whip?duplicate=false?equipable=true
```

Any feedback? I have not had previous experience authoring a "proper" API - and have been just reading and testing lots of different solutions in different development environments.

**Comment by Yonkai** [comment]
Hey @osrsbox, I think both a REST API via a framework (like Eve as you pointed out) and a GraphQL implementation would satisfy the requirements of having dynamic queries for the dataset similar to your typed python code.

It is somewhat of a contentious issue on which is better, but I think ultimately they're [pretty similar when shown side by side. ](https://blog.apollographql.com/graphql-vs-rest-5d425123e34b) There's a [Python implementation of GraphQL too](https://github.com/graphql-python/graphene)  which appears to be extremely active. 

I forked the repo, if I do end up making/working on a GraphQL or REST implementation in any language I'll probably let you know.

Super cool project btw.

**Comment by osrsbox** [comment]
Update: As documented in #157 - the new RESTful API is planned for release in January 2020. Lots of work has been done, and in the final planning and development stages.

**Comment by osrsbox** [comment]
With the informal release of the new API, this issue is nearly resolved. The new API is located at:

- Live site: [https://api.osrsbox.com](https://api.osrsbox.com)
- Development repository: [osrsbos-api](https://github.com/osrsbox/osrsbox-api)

Probably the most useful starting link is the Swagger UI where the API can be investigated and tested informally, available at:

- [https://api.osrsbox.com/swaggerui](https://api.osrsbox.com/swaggerui)

I will document the API further in the future, but to provide some simple examples:

- Get Abyssal whip with known ID number:
    - [https://api.osrsbox.com/items/4178](https://api.osrsbox.com/items/4178)
-  Get all items: 
    - [https://api.osrsbox.com/items/](https://api.osrsbox.com/items/)
    - Then use pagination to continue:
    - [https://api.osrsbox.com/items?page=2](https://api.osrsbox.com/items?page=2)
- Search for items named `Coins`
    - [https://api.osrsbox.com/items?where={"name":"Coins"}](https://api.osrsbox.com/items?where={"name":"Coins"})
- Search for items named `Coins` and find the non-duplicate item
    - [https://api.osrsbox.com/items?where={"name":"Coins","duplicate":false}](https://api.osrsbox.com/items?where={"name":"Coins","duplicate":false})

Feedback is always useful, so free to post here, or on the Discord channel.

**Comment by osrsbox** [comment]
The new API has been up and running for a while now. Everything seems stable is being used. This issue is now closed.

**Comment by TimLehner** [comment]
@Yonkai I am working on implementing a GraphQL API for osrsbox-db. It's still very much a work-in-progress. I have an example deployment you can play with here https://osrs-graphiql-explorer.herokuapp.com/
