### ISSUE TITLE
Item Requirements: Green D'Hide Vambs

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#155]
Green D'hide Vambs incorrectly have a 40 defense requirement instead of a 40 range requirement:

https://www.osrsbox.com/osrsbox-db/items-json/1065.json

**Comment by osrsbox** [comment]
Oops, I made a small typo in this issue.

```
    "1065": {
        "range": 40
    },
```

I will change this to `ranged` instead of `range` now, but will wait to push it when I do another update that I have planned tomorrow.
