### ISSUE TITLE
Add monster database (long-term goal)

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#16]
It has been a goal of mine to add a bestiary to the osrsbox-db. This process has already begun and have written and added OSRS Wiki data extraction scripts to the `extraction_tools_wiki` folder. Have also added some base code for the building of the database to the `bestiary_db_tools` folder. 

This issue will be used for notes and updates on progress.

**Comment by osrsbox** [comment]
I will work on dividing up the tasks to get a list of subtasks. As a side note, if there are specific data property that is more important to you (e.g., monster attack/defence stats) we could prioritize implementing that part first. Currently, the major challenge (in terms of time and complexity) is cleaning the data extracted from the OSRS Wiki.

**Comment by nwalsh1995** [comment]
Okay cool. I am interested in getting Monster defence stats. Eventually will want to have their attack stats, but for now the defence is good.

Let me know if I can help with cleaning the extracted data.

**Comment by osrsbox** [comment]
This monster database has (finally) been authored. The [`monsters-database-dev` branch](https://github.com/osrsbox/osrsbox-db/tree/monsters-database-dev) has the implemented monster database, and the data has been generated. I think that this addition will require more development in the future, but I think i that it would be useful to PR the development branch into the `master`/PyPi package to allow easy testing by others.

@nwalsh1995 - it has been a long time since we first started working on this, but if you are still interested, please feel free to provide any feedback.

Some important additions are:

- `docs/monsters-json`: All of the individual JSON files with monster data
- `test/monster_schema.json`: The JSON schema outlining the properties
- `monsters_builder`: Code used to build the monster database from cache and wiki data
- `osrsbox/monsters_api`: The Python API for the monster database to be incorporated into the `osrsbox` PyPi package
- `osrsbox/monsters_api_examples`: One simple example of the monsters Python API

One interesting note: There is a property named `incomplete` that has been added which indicates when the OSRS Wiki is lacking data for a specific monster. After testing, multiple monsters (usually monsters with low popularity) had properties missing, so I added this property to indicate when wiki data was missing.

A selection of additional work is still required to finalize some small things, including:

- Update `osrsbox/README.md` to include documentation on monsters database
- Update `README.md` to include documentation on monsters database
- Test PyPi package with the addition of the monsters database
