### ISSUE TITLE
Item Requirements: Twisted Slayer Helmet (i)

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#172]
The Twisted Slayer Helmet (i) incorrectly has a defence requirement of null. 

This should be changed to defence: 10

Item ID: 24444
https://www.osrsbox.com/osrsbox-db/items-json/24444.json

**Comment by osrsbox** [comment]
Hey @jburleigh1 - thanks for reporting this, will fix it. Adding to this issue: when using 'builders/items' the program should quit gracefully when an item is equipable and does not have an entry in the item skill requirement JSON file. This way, hopefully, I won't forget to add skill requirements for new items.
