### ISSUE TITLE
Item Requirements: Nightmare Staff Variations

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#173]
The three nightmare staff variations are incorrectly listed with a magic level requirement of 65. All three should have a magic level requirement of 75.

Harmonised nightmare staff | 24423
-- | --

https://www.osrsbox.com/osrsbox-db/items-json/24423.json

Volatile nightmare staff | 24424
-- | --

https://www.osrsbox.com/osrsbox-db/items-json/24424.json

Eldritch nightmare staff | 24425
-- | --

https://www.osrsbox.com/osrsbox-db/items-json/24425.json

**Comment by osrsbox** [comment]
Thanks for reporting this issue - I set all the staff variations with the magic requirements for the normal staff. This was closed in 6f52a5eb477edd77d1b9af6f95b4d1a672024e1d
