### ISSUE TITLE
items-json-slot/items-weapon.json do not contain two-handed weapons

### ISSUE THREAD

**Issue by Antimated** [osrsbox/osrsbox-db#179]
Pretty self-explanatory. There are no two-handed weapons found on the  itemst-json-slot api:
https://www.osrsbox.com/osrsbox-db/items-json-slot/items-weapon.json

Tried looking for spears and greataxe but wound up empty handed :/. Not sure if there is another url needed to get these weapons

**Comment by osrsbox** [comment]
Hey @Antimated - the weapons are divided into two files: `weapon` for one handed weapons, and `2h` for two handed weapons. These naming conventions are used as the OSRS Wiki uses the same names - and I pull weapon slot data from the wiki. Use the `2h` file if you want the two handed weapons as well:
https://www.osrsbox.com/osrsbox-db/items-json-slot/items-2h.json

Confusingly, in the RESTful API (api.osrsbox.com), the `weapons` endpoint includes both types of weapons. The JSON files you are using are the older version before the new API, so probably not changing them into one file - as people use these and wouldn't expect the change. Hope that helps. And please feel to reopen this issue or comment back if you want any more info.
