### ISSUE TITLE
Add tests to existing code

### ISSUE THREAD

**Issue by nwalsh1995** [osrsbox/osrsbox-db#18]
From what I have seen there is little to no testing of the existing code. This can be very detrimental if something is changed and it breaks code further down the line.

We should add testing to this and set something up on TravisCI so that builds automatically happen and we can ensure that all tests pass.

**Comment by nwalsh1995** [comment]
What files do you want to add to testing next @osrsbox ? Not sure which scripts are more important to work on now that we have good coverage of the package.

**Comment by osrsbox** [comment]
Hey @nwalsh1995 - hmmmmmm... I am not too sure what we should aim for next. Like you mentioned - most of the important `osrsbox` package related code is covered. But there could definitely be some useful unit tests added to other code parts, such as the wiki extraction tools, or the items builder. My next major priority at the moment is the monster database. If you have any ideas about missing unit tests, happy to have any input on the matter.

**Comment by osrsbox** [comment]
@nwalsh1995 - having another think about it. I really think we need to add in a test to type check the item database contents. I am consistently modifying the `items_builder` code when re-creating the item database. The `items_api` used to type check the data being used to populate the ItemDefinition, but after modification, then removal of the setters/getters, there is no more type checking. I think it would be best if the test read in the `items-complete.json` file, or `items-json` folder and checked every property of every item.

I wouldn't mind writing the test, but have not yet thought of an elegant solution. Basically, each property in the item needs to be checked to ensure it is the correct type (e.g., int, string, boolean etc.).

**Comment by osrsbox** [comment]
Closing this issue. Any additional testing related issues and add the new `tests` label.
