### ISSUE TITLE
Add Poison Type/Damage

### ISSUE THREAD

**Issue by Khaled431** [osrsbox/osrsbox-db#190]
The wiki now contains more information about poison.

Formats:
https://oldschool.runescape.wiki/w/Zulrah  ``Yes (Venom)``

https://oldschool.runescape.wiki/w/Poison_spider#Level_64  ``Yes (6)``

https://oldschool.runescape.wiki/w/Goblin ``No``

**Comment by osrsbox** [comment]
Just an update on this issue. Added the `venom` property to the data around December. Did not add damage amount as a quick review of the data from the wiki showed very inconsistent formatting - and not many monsters had a damage value.
