### ISSUE TITLE
json for model npc location

### ISSUE THREAD

**Issue by BladeBTW** [osrsbox/osrsbox-db#195]
Hello;
I am using your osrsbox python package and the .jsons located in your docs to build a 3D pipeline from the cache to Blender.
I am able to extract a lot of data and automatically import a bunch of models into Blender; I am very grateful for your work!
I was wondering; when it comes to the models would it be possible to somehow determine for humanoid npcs which model id is used where?
So for example I know that model_id "332" is used for the arms of Valaine but also for a whole lot of other characters. If I can somehow determine that this is an arm model through python I could make a folder with just arm models; and I could do the same for head models etc. # @

**Comment by osrsbox** [comment]
Hey @BladeBTW - unfortunately I do not know the answer to this question. I have also struggled with trying to "map" specific models to NPCs. No idea on how they could be classified based on the model type (e.g., arms). Will leave this issue open for a while, just in case someone reading may know the answer.

**Comment by osrsbox** [comment]
Going to close this issue - as no response from anyone else, and no suitable solution I know of exists. Happy to make a change to the way the models summary file is generated if there is some data in the cache that can be leveraged to get this information.
FYI - the script for generating the models summary is available from: https://github.com/osrsbox/osrsbox-db/blob/master/scripts/cache/generate_summary_models.py
