### ISSUE TITLE
Incorrect duplicate value for Mythical cape

### ISSUE THREAD

**Issue by LucasThole** [osrsbox/osrsbox-db#206]
The 'Mythical cape' (id 22114) on the equipment endpoint has its duplicate value set to 'true'. I believe this should be changed to false as this is not a duplicate.

https://api.osrsbox.com/equipment?where={%22name%22:%22Mythical%20cape%22}

**Comment by osrsbox** [comment]
Hey @LucasThole - just had a look at this issue. I agree. It seems the mounted mythical cape "stole" the duplicate property - as they both share the exact same name and the mounted version has a lower item id value.

This is an easy fix in the project and I will make the change after the next game update. Thanks for reporting the issue! Will close when it is resolved.
