### ISSUE TITLE
Missing Abyssal Sire from monsters_api

### ISSUE THREAD

**Issue by MathieuDR** [osrsbox/osrsbox-db#211]
Abyssal Sire also has multiple known NPC ID's. 

Only `5889` is missing data. Again, we suspect that this is the NPC ID that drops the loot, thus resulting in a 404 error.

**Comment by osrsbox** [comment]
Hey @MathieuDR - seems like a similar issue to #208 where the monster is not deemed attackable. But I can add in the monster as the wiki data uses this ID and is available.

**Comment by osrsbox** [comment]
Closing this issue, as per the comment is issue #210. Also see comment: https://github.com/osrsbox/osrsbox-db/issues/210#issuecomment-782773472
