### ISSUE TITLE
Just tried downloading OSRSBox, May need Advice!

### ISSUE THREAD

**Issue by Thynxy** [osrsbox/osrsbox-db#213]
Does this mean its working? if not what is the issue and how do i rectify it?

https://ibb.co/VT4KDXF

**Comment by osrsbox** [comment]
Hey @Thynxy - I haven't updated that tool for a while and has some bugs. Try getting an old version of the cache which will solve that problem. Have a look at: https://www.osrsbox.com/blog/2020/06/28/osrs-cache-archive/. Also, have a read of the comments on the model dumper blog post for more info.

Closing this issue now as it is not specifically related to this repo. But feel free to ask in the osrsbox discord server if you need more help.
