### ISSUE TITLE
Typo in description of Superhuman Strength

### ISSUE THREAD

**Issue by Jellicott1** [osrsbox/osrsbox-db#214]
The description field of the superhuman strength prayer reads:

"Increases your attack by 15%."

but should be:

"Increases your attack by 10%."

in line with the correct value in the bonuses field. (It's a small thing but I'd rather not have to manually correct this in the current project I'm working on)

**Comment by Jellicott1** [comment]
Ironically there is also a typo in my issue, clearly, the correct description should be:

"Increases your strength by 10%"

not attack.

**Comment by osrsbox** [comment]
Hey @Jellicott1 - thanks for pointing this out. Just doing the weekly update today - and will make this fix.

**Comment by osrsbox** [comment]
Closed in aa863fc3ac1b3d447859dab9a194ed2515ae35c9
