### ISSUE TITLE
Drops missing for certain Monsters (Dark wizard, Giant frog)

### ISSUE THREAD

**Issue by blakeaholics** [osrsbox/osrsbox-db#224]
First off, love the project. Keep up the good work.

Secondly, it appears drops are missing for monsters like Dark wizards and Giant frogs.
The drops disappeared a little while ago, previously working just fine. There may be some others that I haven't noticed yet.

Viewable here: https://api.osrsbox.com/monsters?where=%7B%20%22name%22:%20%22Giant%20frog%22%7D

**Comment by osrsbox** [comment]
Hey @blakeaholics - this should be solved in the next release of the project. The wiki changed how they did drops, and I didn't notice in the last release. Feel free to open the issue again if you keep experiencing problems!
