### ISSUE TITLE
Missing NPC attributes

### ISSUE THREAD

**Issue by Z-Kris** [osrsbox/osrsbox-db#227]
These two attributes can never be found in the json dumps, despite being on the wiki:

[Spectral](https://oldschool.runescape.wiki/w/Spectral_(attribute))
[Golem](https://oldschool.runescape.wiki/w/Golem_(attribute))

**Comment by osrsbox** [comment]
Thanks for reporting. About to push an update that will fix this, and add two new attributes `spectral` and `golem`. Please feel free to reopen if the update does not fix this issue.
