### ISSUE TITLE
Many item icons are now blank

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#232]
It seems with the last update, many of the item icons are now displaying as blank. For example all of the Justicar items:

https://www.osrsbox.com/osrsbox-db/items-icons/22326.png

**Comment by osrsbox** [comment]
Should be fixed in the next update. Seems to be a problem with a new plugin I was using to dump item icons.

**Comment by osrsbox** [comment]
Think this should be solved now... but feel free to reopen if it is not!
