### ISSUE TITLE
Update all code to adhere to PEP8

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#25]
Update code base to adhere to PEP8 using flake8.

**Comment by nwalsh1995** [comment]
Just wondering if this issue can be closed due to #26

**Comment by osrsbox** [comment]
Hey @nwalsh1995. I thought about closing the issue after merging #26 - where the changes resulted in passing all `flake8` tests. But after running `pylint` against the project, there were are large amount of problems. I was worried that the `flake8` tests might be a little lenient and am currently looking into two solutions:

1. Update `flake8` configuration to be more strict
1. Switch to `pylint` and create a customized config file

I am still reading more about PEP8 and each of the tools - looking for the best approach. Wondering if you have any feedback on the matter?

**Comment by nwalsh1995** [comment]
I use flake8 and have no problems with its standard output. That being said, I have never used pylint before so I don't think I can give you any valuable feedback.

Which parts did you want to make more strict for flake8?

**Comment by osrsbox** [comment]
Closed in 15e506261880ac371eedcfc68d990e9ddba88ea6
