### ISSUE TITLE
Type of quest_item property is not always boolean

### ISSUE THREAD

**Issue by Austin-Schmidli** [osrsbox/osrsbox-db#52]
The documentation indicates that the quest_item property is boolean. However for some items, the quest_item property is actually a String array, containing a single quest name. Item ID 10500 demonstrates this issue.

Searching items-complete.json for `"quest_item": [` shows 17 items where this is the case. 

This issue arose when I was parsing items-complete.json for use in another project. I wanted to bring this to attention in case it may cause future problems down the road.

**Comment by osrsbox** [comment]
@Austin-Schmidli - thank you very much for reporting this issue. 

Last week I changed the `quest` property from an Array of quest names, to a boolean to show quest association (if the item is associated with a quest). The array of quest names was not reliably accurate (but may return in the future). Looks like a couple of items were missed in the change.

I will update these problematic items in the next item database update. So just after the next in-game update.

**Comment by osrsbox** [comment]
Quick update. Problematic items are listed below:

````
10500 Crone-made amulet
2529 Dead orb
286 Orange goblin mail
287 Blue goblin mail
3695 Pet rock
4202 Ring of charos
5056 Dwarven battleaxe
5057 Dwarven battleaxe
5058 Dwarven battleaxe
5059 Dwarven battleaxe
5062 Left boot
5063 Right boot
5064 Exquisite boots
5067 Exquisite clothes
6788 Torn robe
6789 Torn robe
6818 Bow-sword
````
