### ISSUE TITLE
Serp Helm variants (tanzanite and magma) have incorrect stats.

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#7]
The serpentine helm has two variants, charged and uncharged. The stats in the DB reflect the charged version as seen here:

https://www.osrsbox.com/osrsbox-db/items-json/12931.json

For the Tanzanite and Magma variants, the stats in the DB reflect the uncharged version as seen here:

https://www.osrsbox.com/osrsbox-db/items-json/13197.json

and

https://www.osrsbox.com/osrsbox-db/items-json/13199.json

**Comment by osrsbox** [comment]
This issue has been closed in 2e838ab4b29c3f4c20f8eef13cba4339c5b439eb.
All items with versioned Infoboxes on the OSRS Wiki should now have correct properties and bonuses. The code changes to parse versioned Infoboxes was 3125c746c8702c25b9654f08546415b419a2c9cc.
