### ISSUE TITLE
Noted items are showing as non-tradable in the allitems.json file

### ISSUE THREAD

**Issue by sheymyster** [osrsbox/osrsbox-db#8]
Hello! I love the projects you're working on and was hoping to utilize the all-items json file in my own project. I noticed that currently, any item that is noted shows as "tradeable": false, but notes are tradeable. If I'm reading it wrong let me know, otherwise figured you'd want to know about the error. 

Thanks again!

**Comment by osrsbox** [comment]
Hey @sheymyster. Thanks for reporting this issue. I was hoping that you could please supply an example of the issue you described? A couple of item ID numbers would really help me find this bug, and make sure I am seeing the same issues as you. From your description, I think you are reading the values correctly.

Below is an example that I think summarizes your issue:

```
{
   "1079":{
      "stackable":false,
      "quest_item":false,
      "examine":null,
      "equipable":true,
      "noteable":true,
      "noted":false,
      "name":"Rune platelegs",
      "tradeable":true,
      "id":1079
   },
   "1080":{
      "stackable":true,
      "quest_item":false,
      "examine":null,
      "equipable":false,
      "noteable":true,
      "noted":true,
      "name":"Rune platelegs",
      "tradeable":false,
      "id":1080
   }
}
```

This information is a snipped version from the `items_itemscraper.json` file that is taken directly from the OSRS cache. It seems that Rune platelegs are tradeable when not noted, but not tradeable when noted - which as you mentioned - is not the case! I haven't tested this in game, but pretty sure you can trade Rune platelegs with other players in noted form. I will check this, and also have a look into this issue further.

**Comment by sheymyster** [comment]
Sure thing! So, when you view your file as RAW through Github (because it's too large to display normally I suppose), the first thing that pops up is Guam Potion (unf) which is ID 92. This is the noted formed of Guam Potion (unf), but (unf) potions are tradable. 

That's when I checked further because I wanted to see if the issue recurred for other ID"s. 

Noted Raw karambwan ID 3143
Noted Soft clay ID 1762
Noted Dragon 2H ID 7407

As far as I can tell, every single noted item is marked as non-tradeable. I suppose when you scrape somehow it picks that up, not sure how though as I haven't looked too deep into your scraper code. 
Unless I'm forgetting some special circumstance, I'd say if an item has noted and non-noted form, if the non-noted is tradeable, so is the noted so that may be an easy fix to correct the data. 

Also, I found one other odd thing. It appears you have some items duped with 2 different ID's. The only one I found were arrows. For example, Rune arrow is listed once for the number I'm used to (ID 892). It's all correct I believe, but Rune arrow is listed again at ID 14577. I've looked on a few other websites with ID databases to try to see where this number came from, but I have no idea. Just figured I'd bring it up, but if you'd like me to create a separate "issue" on github to keep things in their own conversations, let me know and I'll do that. 

Thanks again for your hard work on this! Let me know if you'd like me to provide any other info to help get a fix.

**Comment by osrsbox** [comment]
Hey @sheymyster, thanks very much for taking the time to post some examples. They really help. 

I double checked the code used to determine the `tradeable` property, which seems to be functioning fine. Like I mentioned, the data is pulled from the cache and the extraction method works fine. I tested with multiple cache tools (and my own), and kept getting the same results. But I agree with you... it seems possible to trade noted variations of the items you have listed. So there is a discrepancy in the data. I still need to do some more testing in-game to ensure this is correct before proceeding with a change in the database. I will post updates here as I progress.

Also, yes - there are some duplicates in the database. Another user and I have also been discussing this. I opened another issue #9, if you want to be informed on progress.

**Comment by osrsbox** [comment]
Just a small update on this issue. I have performed some more investigation and have a solution to this issue. It seems the `tradeable` property should really be renamed to something like `tradeable_on_ge`. All items that are `tradeable` seem to be only tradeable on the Grand Exchange, rather than being tradeable between players.
 
*Solution*: 
1. Change `tradeable` property name to `tradeable_on_ge`
1. Populate existing `tradeable` property with the tradeable information taken from the OSRS Wiki

There is also a new property in the database called `linked_id`. This can be used to determine if the linked item (the noted, or unnoted variant of the item) is tradeable. If either is tradeable, both should be tradeable.

I will work on fixing and closing this issue in the near future.

**Comment by sheymyster** [comment]
Thank you so much man! You rock! I actually built a small script in node to iterate through your RAW file and just change every item that had a tradeable version unnoted and a noted non-tradeable version. There's too many items for me to actually check if I didn't screw some of them up though, haha. I look forward to using your updated raw output once you get the scraping script fixed. Thanks again for all of your work on this and other projects. I also took some time to read through your runelite plugin tutorials and hope to mess around with that in the future (I don't know the language though so bit of a learning curve but your tuts help).

**Comment by osrsbox** [comment]
Hey @sheymyster, just pushed changes to the item database that now have:
- `tradeable`: items tradeable on the GE **or** player to player (based on OSRS Wiki content)
- `tradeable_on_ge`: items tradeable only on the GE

I did a pretty thorough check on the items, so pretty sure everything went smoothly. Always happy to address any problems you find. But for now, I have closed this issue.
Also, thanks very much for your kind words. And very happy that this project is of use to people! And if you want any types of tutorials written on my blog that would be helpful please feel free to ask - I like to hear what people are interested in. Anything technical (mainly programming related or data related) is of real interest to me.
