### ISSUE TITLE
Fix incorrect thumbnail

### ISSUE THREAD

**Issue by CHBresser** [osrsbox/osrsbox-db#80]
Thumbnail image for Item 3147: cooked karambwan shows a poison karambwan. 

https://www.osrsbox.com/osrsbox-db/items-icons/3147.png

**Comment by osrsbox** [comment]
Hey @CHBresser, thanks for the issue submission. You are definitely correct that the 3147 item id shows a poison karambwan, and the item name has "cooked". The item icons are extracted directly from the game cache, so this is definitely the correct image for this item id - based on the in-game data. Looking at the karambwan associated IDs, I got the following list:

```
Cooked karambwan | 3144 - normal cooked version
Cooked karambwan | 3145 - normal cooked noted version
Poison karambwan | 3146 - poison version
Cooked karambwan | 3147 - the item in question
```

So for some reason, 3147 is a cooked karambwan with the icon for a poisoned one.... Hmmmm. There is usually a reason for "strange" items like this one. I seem to remember that part of the Tai Bwo Wannai Trio quest is to "cook" a karambwan that ends up poisonous? This might be the item for that quest?

I am taking the in-game data (e.g. cache data) as being correct - so don't really want to change the icon, when it is probably a special item id with another purpose. If you want the cooked version of the icon , 3144 is the correct one. 

This is a really hard scenario that pops up lots with the items - multiple IDs for seemingly the same item. Bit I want to keep every in-game item id in the database.

**Comment by osrsbox** [comment]
Closing this issue, but feel free to comment/reopen if needed.
