### ISSUE TITLE
Seasonal/DMM items should be marked as separate

### ISSUE THREAD

**Issue by nwalsh1995** [osrsbox/osrsbox-db#82]
Hi @osrsbox,

I was playing around with the armor database and ended up getting some results on items that I didn't know existed! Looking them up, they were seasonal DMM items: ex: https://oldschoolrunescape.fandom.com/wiki/Vesta%27s_spear

I was wondering if there is interest in adding some type of flag that marks these as DMM only, or if that data can already be obtained. I want to avoid items that do not exist in the 'normal' game mode. For now, I can filter these out by item name in my code but it would be nice if there was a flag that we could use.

**Comment by osrsbox** [comment]
@nwalsh1995 - This is an interesting set of items. According to the [Ancient Warriors' equipment](https://oldschoolrunescape.fandom.com/wiki/Ancient_Warriors%27_equipment) page on the OSRS Wiki, there are a total of 17 unique items. So there will be 51 affected items in the database (one for the equipable item, one for the noted item, and one for the placeholder item). I remember when they were released, and noticed I was adding them into the database when they were not in the "normal" game.

Unfortunately, there is no flag/attribute in the data I use to help identify these items. I could add an attribute to identify them, and mark them as `dmm_only` with a boolean, or something similar. I would use a similar solution to what you mentioned (identify by static name, or ID number). 

I am not sure if it is worth it adding another property to the current schema. It just seems that adding in a new property for 50 items out of ~20,000 is not that worthwhile. I am not sure how useful it would be... but I am open to changing my mind, especially if you (or anyone else) thinks it would be really useful. Also, it would be a pretty easy change to make. Let me know how strongly you feel about adding a new property!

**Comment by nwalsh1995** [comment]
Yeah, I think there can be a few problems if we accept just adding all kinds of attributes. Personally, I would love this attribute since I would be using it so I am biased :P. It depends how encompassing you want the database to be. There are a few things that I can think of a problem: someone relies on your DMM item check and later items are added from DMM that do not have the flag, so a new issue will be opened and you must manually maintain the database for these items.

Just from that use case of maintainability I would be hesitant to add something we cannot detect purely from code. Unfortunately, it might be best to just put this off on the user.

**Comment by osrsbox** [comment]
@nwalsh1995 - I was thinking more about this issue and have thought of a solution that overlaps with another issue. In the game cache there are a number of items that are not actually available in-game. The OSRS Wiki lists these as [Unobtainable items](https://oldschool.runescape.wiki/w/Unobtainable_items).

I was thinking of adding a new property called `unobtainable` and adding setting it for `true` for all the items listed in the OSRS Wiki - as I think this is pretty useful information. I already have these items populated in the `normalized_names.txt` file. I could add Ancient Warriors' equipment to this list, indicating that they are not available in-game. It is not the most accurate solution - as they technically are obtainable. But thought this solution would be more efficient in terms of additional properties required. Any thoughts on this solution?

**Comment by nwalsh1995** [comment]
The only problem that I have with your suggestion is that the items are not `unobtainable`, as they can be obtained in DMM. For my app, the best case is to have a toggle where someone can say they are DMM or not, so I can show the proper items available to them. From your suggestion I think this solution would not address that.

Personally, I think two options might be the best way forward, either add the DMM flag or do not add this type of information in at all.

**Comment by osrsbox** [comment]
I just closed this issue in 07124c682b6848da55bf8166a3272a3c8aebe7ec. I was a little unsure of how to proceed, so I took the middle ground and added a new file named: `dmm-only-items.json` in the `data` folder. Maybe this could be added in to the full item database later... but for now it adds the data in a logically structured manner for developers to use.
