### ISSUE TITLE
Change skill requirements array to object

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-db#84]
As suggested by @jburleigh1 - change the `skill_reqs` list to an object... It makes much more sense to store the data as an object! Example of the current storage method:

```
      "skill_reqs": [
        {
          "skill": "magic",
          "level": 40
        },
        {
          "skill": "defence",
          "level": 40
        }
      ]
```

Which would be changed to the following:

```
      "skill_reqs": {
          "magic": "40",
          "defence": 40
        }
```

This change requires modifying the following:

- items builder
- item API
- documentation
- skill requirements generation script

EDIT: It would also make sense to change the key for this object to a more generic name. I am thinking that `requirements` would be suitable - and the object could be expanded in future to house additional information (e.g., maybe quest requirements, an additional description etc.)

**Comment by jburleigh1** [comment]
Thank you!
